import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {RoundedBoxGeometry} from './vendor/RoundedBoxGeometry.js';
import {rooms,walls,obstacles,roomAt,canStand,findPath,activities,entryStep,floorHeight,planToWorldX,worldToPlanX} from './layout.js';
const $=id=>document.getElementById(id);let focused='all',selected=0,hour=16.5,weather='sun',timeRunning=true,fullWalls=false,planMode=false,routine='random';
const state={entry:true,kitchen:true,wash:false,bath:false,living:false,desk:true,computer:true};
let toastTimer;function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200)}
const scene=new THREE.Scene();const spatial=new THREE.Group();spatial.scale.x=-1;spatial.position.x=3;scene.add(spatial);scene.background=new THREE.Color('#efddb5');const camera=new THREE.PerspectiveCamera(36,1,.1,120);camera.position.set(10,13,-8);let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;$('canvasHost').appendChild(renderer.domElement)}catch(e){$('loading').hidden=true;$('sceneError').hidden=false;throw e}
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(1.5,0,4.3);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=2.2;controls.maxDistance=25;controls.maxPolarAngle=Math.PI/2.08;controls.minPolarAngle=.1;controls.enablePan=true;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};
const hemi=new THREE.HemisphereLight('#fff4d5','#a57d53',1.2);spatial.add(hemi);const sun=new THREE.DirectionalLight('#ffe3a3',3.2);sun.position.set(-1,5,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-8,right:8,top:8,bottom:-8,near:.1,far:35});sun.shadow.bias=-.00015;sun.shadow.normalBias=.015;sun.target.position.set(1.5,.1,5);spatial.add(sun,sun.target);
const moonLight=new THREE.DirectionalLight('#99bded',.12);moonLight.position.set(5,6,12);spatial.add(moonLight);
const world=new THREE.Group();spatial.add(world);const groups={};rooms.slice(1).forEach(r=>{groups[r.id]=new THREE.Group();groups[r.id].userData.room=r.id;world.add(groups[r.id])});
const interactables=[],floors=[],wallMeshes=[],lamps={},doors=[];const matCache=new Map();function mat(c,rough=.75){const key=c+rough;if(!matCache.has(key))matCache.set(key,new THREE.MeshStandardMaterial({color:c,roughness:rough}));return matCache.get(key)}
function box(g,x,y,z,w,h,d,c,r=.035){let geometry=r?new RoundedBoxGeometry(w,h,d,2,Math.min(r,w/3,h/3,d/3)):new THREE.BoxGeometry(w,h,d);let mesh=new THREE.Mesh(geometry,typeof c==='string'?mat(c):c);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh}
function sphere(g,x,y,z,r,c,scale=[1,1,1]){const m=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),typeof c==='string'?mat(c):c);m.position.set(x,y,z);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
function cyl(g,x,y,z,r,h,c,rt=r){const m=new THREE.Mesh(new THREE.CylinderGeometry(rt,r,h,20),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
function bar(g,a,b,r,c){let m=cyl(g,0,0,0,r,new THREE.Vector3(...a).distanceTo(new THREE.Vector3(...b)),c);m.position.copy(new THREE.Vector3(...a).add(new THREE.Vector3(...b)).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(...b).sub(new THREE.Vector3(...a)).normalize());return m}
function click(mesh,id){mesh.userData.action=id;interactables.push(mesh);return mesh}
const C={wood:'#cd9f60',light:'#f5e4bd',cream:'#fff0cf',wall:'#f5dfa9',dark:'#685241',blue:'#8baebd',metal:'#a9b6b2'};
// Every rendered room shares its coordinates with the navigation model and SVG plan.
for(const r of rooms.slice(1)){const[a,b,c,d]=r.rect,g=groups[r.id];if(r.id==='entry'){
 const low=box(g,(a+c)/2,-entryStep.height-.095,entryStep.z/2,c-a,.19,entryStep.z,'#bcb49f',.012);low.userData.room=r.id;floors.push(low);
 const high=box(g,(a+c)/2,-.095,(entryStep.z+d)/2,c-a,.19,d-entryStep.z,'#d5ac6d',.012);high.userData.room=r.id;floors.push(high);
 // Vertical timber riser, flush with the interior floor, not a raised threshold.
 box(g,(a+c)/2,-entryStep.height/2,entryStep.z+.008,c-a,entryStep.height,.016,'#ad814d',.002);
 for(let x=.3;x<c;x+=.3)box(g,x,-entryStep.height+.002,entryStep.z/2,.006,.002,entryStep.z-.015,'#a89f89',0);
 for(let z=.3;z<entryStep.z;z+=.3)box(g,(a+c)/2,-entryStep.height+.002,z,c-a-.02,.002,.006,'#a89f89',0);
 for(const x of [0,c])box(g,x,-entryStep.height/2,entryStep.z/2,.08,entryStep.height,entryStep.z,'#d4c29f',.005);
}else{const f=box(g,(a+c)/2,-.095,(b+d)/2,c-a,.19,d-b,r.id==='bath'?'#e5dac1':r.id==='wash'?'#e7d4af':r.id==='balcony'?'#d7c5a2':'#d5ac6d',.028);f.userData.room=r.id;floors.push(f);}if(['living','kitchen'].includes(r.id)){for(let x=a+.02;x<c;x+=.165){box(g,x,.005,(b+d)/2,.008,.003,d-b-.03,'#bb915d',0);for(let z=b+((Math.round(x*10)%2)*.35)+.5;z<d;z+=1.12)box(g,x+.079,.008,z,.151,.003,.006,'#bf9761',0)}}else if(['bath','wash','balcony'].includes(r.id)){for(let z=b+.3;z<d;z+=.3)box(g,(a+c)/2,.006,z,c-a,.004,.006,'#c8b897',0)}}
// Invisible-in-color ceiling keeps sunlight entering through the real balcony opening.
for(const r of rooms.slice(1).filter(r=>r.id!=='balcony')){const[a,b,c,d]=r.rect;const roof=box(groups[r.id],(a+c)/2,2.32,(b+d)/2,c-a,.04,d-b,new THREE.MeshBasicMaterial({colorWrite:false,depthWrite:false}),0);roof.receiveShadow=false;roof.castShadow=true;}
// Foundation and quiet circular stage.
box(world,1.5,-.26,4.3,3.15,.22,8.75,'#b99155',.065);const stage=cyl(spatial,1.5,-.43,4.3,7,.12,'#e4c997');stage.receiveShadow=true;
for(const[a,b,c,d,owner]of walls){let room=groups[owner]?owner:(b>=4.3?'living':b>=1.65?'kitchen':'entry'),g=groups[room];let m=box(g,(a+c)/2,1.13,(b+d)/2,Math.abs(c-a)+.09,2.26,Math.abs(d-b)+.09,new THREE.MeshStandardMaterial({color:C.wall,roughness:.92,transparent:true}),.02);m.userData.bound=[a,b,c,d];m.userData.owner=owner;wallMeshes.push(m);box(g,(a+c)/2,.075,(b+d)/2,Math.abs(c-a)+.11,.13,Math.abs(d-b)+.11,'#bd955d',.008)}
// Replace full-length outer walls with independently selectable room-length slices.
for(const m of [...wallMeshes]){if(['outerLeft','outerRight'].includes(m.userData.owner)){m.parent.remove(m);wallMeshes.splice(wallMeshes.indexOf(m),1)}}
for(const r of rooms.slice(1)){let[a,b,c,d]=r.rect;for(const x of [0,3])if((a===0&&x===0)||(c===3&&x===3)){const height=r.id==='balcony'?.68:2.26;let m=box(groups[r.id],x,height/2,(b+d)/2,.09,height,d-b,new THREE.MeshStandardMaterial({color:C.wall,roughness:.92,transparent:true}),.025);m.userData.bound=[x,b,x,d];wallMeshes.push(m)}}
function door(g,x,z,w,orientation){let pivot=new THREE.Group();pivot.position.set(x,0,z);g.add(pivot);let p=box(pivot,w/2,1.02,0,w,2.04,.055,'#e4cda0',.02);box(pivot,w-.09,.98,-.042,.035,.07,.025,'#a39478',.008);pivot.rotation.y=orientation;doors.push({pivot,x,z,w,base:orientation});return pivot}
door(groups.entry,.43,.01,.93,0);door(groups.wash,1.55,1.47,.8,-Math.PI/2);door(groups.bath,1.71,2.7,.7,0);door(groups.living,.63,4.3,.8,0);
// Entry: black front door, pale shoe cabinet and mirror.
const entryDoor=doors[0].pivot;entryDoor.position.y=-entryStep.height;entryDoor.children[0].material=mat('#514b42');box(groups.entry,.23,.77,1.29,.42,1.54,.54,C.light);box(groups.entry,.453,1.08,1.29,.009,.8,.37,'#adbab7',0);for(let z of [1.12,1.45])box(groups.entry,.46,.73,z,.024,.1,.035,'#9c8e73');for(let x of [.73,.96]){box(groups.entry,x,.07-entryStep.height,.47,.14,.12,.25,'#f3eee1',.05);box(groups.entry,x,.129-entryStep.height,.43,.1,.035,.06,'#716f64',.012)}bar(groups.entry,[.8,1.1,.09],[.8,.35,.09],.012,'#dacdb0');sphere(groups.entry,.8,.8,.09,.12,'#e1dcca',[.65,2,.35]);
// Kitchen: dark linear counter, cooker, sink, refrigerator and appliances.
const k=groups.kitchen;box(k,.31,.44,2.58,.58,.86,1.58,C.dark);box(k,.31,.895,2.58,.64,.045,1.62,'#b5b9ad',.018);for(let z of [2.03,2.5,2.97])box(k,.607,.47,z,.025,.63,.43,'#775f48',.014);for(let z of [2.08,2.55,3.02])box(k,.63,.71,z,.03,.02,.17,'#c2b69a');box(k,.29,.93,2.12,.48,.05,.47,'#494a40');for(let z of [1.97,2.24]){cyl(k,.28,.965,z,.105,.014,'#171e1c');cyl(k,.28,1.02,z,.083,.1,'#6b786d');bar(k,[.29,1.035,z],[.55,1.035,z],.014,'#4d5046')}
box(k,.29,.92,2.96,.44,.03,.49,'#798c86',.07);box(k,.29,.928,2.96,.32,.028,.36,'#9fafaa',.06);bar(k,[.14,.94,3.15],[.14,1.17,3.15],.017,'#b8c3b9');bar(k,[.14,1.17,3.15],[.28,1.17,3.15],.018,'#b8c3b9');box(k,.22,1.87,2.56,.44,.47,1.57,C.dark);box(k,.34,1.57,2.13,.57,.16,.56,'#514a3b');for(let z of [2.6,2.84,3.09]){cyl(k,.1,1.035,z,.035,.17,['#d3a04c','#e8e0ba','#b5be8c'][Math.round(z*10)%3]);}
const fridge=box(k,.32,.65,3.82,.6,1.3,.66,'#f3eee0',.05);click(fridge,'fridge');box(k,.625,.68,3.82,.013,.015,.64,'#cabfaa');box(k,.655,1.03,3.98,.035,.23,.04,'#aaa99a');box(k,.655,.37,3.98,.035,.21,.04,'#aaa99a');box(k,.32,1.47,3.82,.59,.32,.49,'#f7f0d9');box(k,.625,1.48,3.82,.013,.21,.32,'#555f58',.016);cyl(k,.3,1.79,3.8,.155,.32,'#fff4dc',.14);box(k,.465,1.79,3.8,.045,.15,.065,'#c0b395');click(fridge,'fridge');
// Washroom has basin + toilet and a storage/laundry niche, without invented windows.
const w=groups.wash;box(w,2.69,.4,2.3,.51,.8,.54,'#c7a16b');box(w,2.69,.82,2.3,.57,.055,.59,'#faf0d9');sphere(w,2.68,.89,2.3,.23,'#fff7e5',[1,.35,1.08]);sphere(w,2.68,.93,2.3,.18,'#d8dccc',[1,.12,1.08]);bar(w,[2.9,.85,2.3],[2.9,1.07,2.3],.017,'#b0baae');bar(w,[2.9,1.07,2.3],[2.78,1.07,2.3],.017,'#b0baae');box(w,2.94,1.47,2.3,.027,.83,.53,'#a3b7b6');box(w,2.917,1.45,2.3,.018,.71,.41,'#bcd0c7');cyl(w,2.77,.47,1.5,.18,.4,'#eeeedd',.14);sphere(w,2.66,.57,1.5,.22,'#fff7e5',[1.18,.35,.82]);sphere(w,2.66,.64,1.5,.16,'#c6d1c5',[1.17,.13,.72]);box(w,2.85,.82,1.5,.21,.47,.43,'#fff7e5');box(w,2.73,1.82,1.57,.49,.57,.78,'#f5edd9');box(w,1.98,.4,.44,.58,.8,.55,'#c29e70');for(let y of [.3,.56])box(w,1.98,y,.731,.51,.18,.015,'#d0b080');bar(w,[1.65,1.76,.47],[2.31,1.76,.47],.016,'#a5aaa0');for(let x of [1.79,1.99,2.17])box(w,x,1.42,.47,.13,.51,.055,x>2?'#b9b395':'#6b665b');
// Recessed tub uses a rim and inner floor, not a solid block.
const b=groups.bath;box(b,2.28,.2,3.95,1.25,.39,.53,'#dedfcb',.065);box(b,2.28,.44,4.23,1.3,.5,.11,'#fff0d7',.035);box(b,2.28,.44,3.66,1.3,.5,.11,'#fff0d7',.035);for(let x of [1.67,2.88])box(b,x,.44,3.95,.1,.5,.55,'#fff0d7',.035);const water=box(b,2.28,.48,3.95,1.05,.016,.44,new THREE.MeshPhysicalMaterial({color:'#9ac6ba',transparent:true,opacity:.72,roughness:.2}),.04);click(water,'bathWater');bar(b,[2.94,.8,3.24],[2.94,1.56,3.24],.016,'#b4bdb0');sphere(b,2.92,1.54,3.24,.072,'#b8c9bd',[.25,1,1]);box(b,2.94,1.02,3.42,.025,.48,.34,'#a7bdb1');bar(b,[1.69,1.85,4.04],[2.84,1.85,4.04],.013,'#b4b2a0');box(b,2.15,1.57,4.04,.62,.57,.027,'#c8b39a');cyl(b,2.78,.12,2.95,.043,.22,'#bba672');
// Living room: right-wall bed, blue bedding, white desk at window, left clothing rack.
const l=groups.living;box(l,2.325,.19,5.5,1.22,.34,2.1,'#b98c50',.045);box(l,2.325,.39,5.5,1.19,.2,2.05,'#e7dec7',.085);box(l,2.325,.505,5.71,1.2,.075,1.52,C.blue,.065);box(l,2.325,.56,5.3,1.2,.07,.5,'#a9babe',.048);box(l,2.325,.53,4.81,.78,.17,.42,'#f8e9cb',.085);box(l,2.325,.56,4.46,1.25,.54,.075,'#c49b60');for(let y of [.45,.65])box(l,2.325,y,4.415,1.1,.045,.025,'#a57c45');for(let x of [1.93,2.5])box(l,x,.13,5.48,.42,.2,1.36,'#e8dac0');click(box(l,2.32,.54,6.23,1.19,.065,.34,'#769eaf',.04),'rest');
box(l,1.89,.765,7.3,1.29,.065,.54,'#fff4db',.025);for(let x of [1.29,2.49])for(let z of [7.08,7.53])bar(l,[x,.03,z],[x,.73,z],.024,'#e7dec9');bar(l,[1.31,.09,7.54],[2.47,.72,7.54],.013,'#dbd4bc');
const laptop=new THREE.Group();laptop.position.set(1.69,.815,7.24);l.add(laptop);click(box(laptop,0,0,0,.47,.026,.29,'#697777',.015),'computer');const lid=new THREE.Group();lid.position.set(0,.005,.12);lid.rotation.x=-.16;laptop.add(lid);box(lid,0,.165,0,.47,.33,.025,'#586965',.016);const screenMat=new THREE.MeshStandardMaterial({color:'#9dbeb6',emissive:'#76c3cb',emissiveIntensity:.65,roughness:.45});click(box(lid,0,.167,-.016,.416,.269,.004,screenMat,.004),'computer');for(let i=0;i<3;i++)box(lid,-.065,.095+i*.049,-.02,.2,.012,.003,'#d1e7d4',0);for(let z of [-.08,-.03,.02])box(laptop,0,.015,z,.33,.004,.009,'#b6c2b6',0);sphere(l,2.13,.825,7.23,.047,'#4d5d54',[.75,.3,1]);cyl(l,2.36,.872,7.16,.039,.15,'#e2b46d');
function chair(g,x,z,c,angle=0){const gr=new THREE.Group();gr.position.set(x,0,z);gr.rotation.y=angle;g.add(gr);box(gr,0,.34,0,.39,.065,.4,c,.04);box(gr,0,.63,-.16,.39,.46,.055,c,.05);for(let xx of [-.14,.14])for(let zz of [-.12,.12])bar(gr,[xx,.03,zz],[xx,.32,zz],.018,'#e1d6b8');return gr}
chair(l,1.88,6.75,'#e4c390',0);chair(l,.36,5.91,'#e9dcc0',Math.PI/2);const book=box(l,.36,.405,5.9,.27,.06,.19,'#ae7057');click(book,'read');
for(let x of [.15,.82])bar(l,[x,.03,7.38],[x,1.87,7.38],.018,'#685d4a');for(let y of [.14,.53,.92,1.86])box(l,.49,y,7.34,.7,.035,.47,'#786b53');bar(l,[.17,1.69,7.38],[.79,1.69,7.38],.018,'#5e594a');for(let x of [.53,.68])box(l,x,1.25,7.39,.14,.71,.13,x>.6?'#696e62':'#b4a586');for(let y of [.29,.67])box(l,.34,y,7.32,.29,.23,.37,'#dfceb0',.028);box(l,.47,1.98,7.35,.29,.2,.23,'#eedeb7');box(l,.53,2.04,7.56,.93,.31,.21,'#f4edd8');box(l,.53,1.938,7.432,.75,.042,.025,'#9a9d8b');
// Balcony glazing: an open central passage, and curtains framing the actual window.
for(let x of [.12,2.88])box(l,x,1.1,7.67,.12,2.2,.11,'#d7c69e');box(l,1.5,2.18,7.67,2.86,.1,.11,'#ddcfae');box(l,1.5,.03,7.67,2.86,.04,.14,'#a69e86');const glassMat=new THREE.MeshPhysicalMaterial({color:'#b8d7ca',transparent:true,opacity:.15,roughness:.2,metalness:.05,depthWrite:false});for(let x of [.43,2.69])box(l,x,1.1,7.69,.57,2.08,.014,glassMat,0);for(let x of [.77,2.4])box(l,x,1.1,7.7,.027,2.1,.035,'#b0ad97');for(let side of [0,1])for(let i=0;i<4;i++){let x=side?2.72+i*.057:.13+i*.057;box(l,x,1.1,7.51,.083,2.01,.11,'#c8b18c',.035)}
const balcony=groups.balcony;box(balcony,1.5,.64,8.59,3,.1,.08,'#9e9b82');for(let x=.12;x<3;x+=.24)bar(balcony,[x,.01,8.59],[x,.62,8.59],.013,'#b0ab8f');box(balcony,.41,.31,8.03,.6,.58,.4,'#e7dcc0');for(let y=.1;y<.5;y+=.07)box(balcony,.41,y,8.242,.47,.016,.015,'#aea78f');
// Decorative city is outside the apartment; it never changes the floor plan.
const outside=new THREE.Group();spatial.add(outside);for(let i=0;i<11;i++){let x=-4+i*1.1,z=11.5+(i%3)*.6,h=.7+(i%4)*.5;box(outside,x,h/2-.18,z,.7,h,.65,'#d3bc93',.07);for(let y=.25;y<h-.1;y+=.4)for(let dx of [-.17,.17])box(outside,x+dx,y,z-.332,.12,.17,.01,'#e9d9ae',.015)}
const moon=sphere(outside,4,4,12,.33,new THREE.MeshBasicMaterial({color:'#fff0bd'}));const sunOrb=sphere(outside,-2,3.7,12,.4,new THREE.MeshBasicMaterial({color:'#ffe1a0'}));const clouds=[];for(let i=0;i<3;i++){let g=new THREE.Group();g.position.set(-3+i*3,3.6+(i%2)*.55,12);outside.add(g);for(let j=0;j<3;j++)sphere(g,j*.23,Math.sin(j)*.13,0,.24,'#ece4ce',[1.3,.85,.8]);clouds.push(g)}
// Rain remains beyond the window and has no indoor particles.
const rainGeo=new THREE.BufferGeometry(),rainPos=new Float32Array(420*3);for(let i=0;i<420;i++){rainPos[i*3]=-5+(i*1.731%12);rainPos[i*3+1]=(i*.43)%5;rainPos[i*3+2]=8.8+(i*.373%5)}rainGeo.setAttribute('position',new THREE.BufferAttribute(rainPos,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:'#94aeb3',size:.025,transparent:true,opacity:.7}));outside.add(rain);
function lamp(id,room,x,y,z,power){let g=groups[room];const material=new THREE.MeshStandardMaterial({color:'#f7da91',emissive:'#ffd885',emissiveIntensity:.8});let bulb=sphere(g,x,y,z,.07,material);click(bulb,'light:'+id);const light=new THREE.PointLight('#ffcb77',power,3.8,2);light.position.set(x,y-.04,z);light.castShadow=true;light.shadow.mapSize.set(512,512);light.shadow.bias=-.002;g.add(light);lamps[id]={bulb,light,power,material,room};return light}
lamp('entry','entry',1,1.92,.8,4);lamp('kitchen','kitchen',.84,1.85,2.6,5);lamp('wash','wash',2,1.92,1.7,4);lamp('bath','bath',2.12,1.92,3.2,3.8);lamp('living','living',1.5,1.96,5.8,7);cyl(l,1.5,2.01,5.8,.19,.12,'#edcb82',.11);
// Desk spotlight: a real shadow-casting light aimed onto the tabletop.
cyl(l,2.32,.809,7.4,.085,.025,'#aa8a48');bar(l,[2.32,.82,7.4],[2.32,1.17,7.4],.015,'#af8e48');bar(l,[2.32,1.17,7.4],[2.16,1.27,7.37],.015,'#af8e48');const shade=cyl(l,2.16,1.24,7.37,.11,.12,'#e5ba5b',.057);click(shade,'light:desk');const deskLight=new THREE.SpotLight('#ffce76',7,2.5,Math.PI/4,.5,1.8);deskLight.position.set(2.16,1.21,7.37);deskLight.target.position.set(1.99,.76,7.21);deskLight.castShadow=true;deskLight.shadow.mapSize.set(512,512);deskLight.shadow.bias=-.001;l.add(deskLight,deskLight.target);lamps.desk={light:deskLight,power:7,room:'living'};
function makePerson(girl,x,z){const root=new THREE.Group();root.position.set(x,floorHeight(x,z),z);spatial.add(root);const body=new THREE.Group();root.add(body);const skin='#f0c9a0',hair=girl?'#5e4031':'#514031',shirt=girl?'#d99a69':'#e0bf76';sphere(body,0,.56,0,.175,skin,[1,1.05,.94]);sphere(body,0,.626,-.033,.18,hair,[1, .73, .89]);for(let i=0;i<3;i++)sphere(body,-.1+i*.09,.657,.098,.07,hair,[.8,.8,.6]);if(girl){sphere(body,-.164,.48,-.035,.064,hair,[.8,1.7,.8]);sphere(body,.164,.48,-.035,.064,hair,[.8,1.7,.8]);sphere(body,.15,.674,-.025,.039,'#f0cf89',[1.4,.7,.8])}for(let xx of [-.062,.062]){sphere(body,xx,.568,.151,.013,'#473a30',[.8,1.1,.5]);sphere(body,xx*1.47,.525,.143,.022,'#e8aa90',[1,.55,.22])}sphere(body,0,.528,.164,.014,skin,[.9,.6,.55]);box(body,0,.33,0,.245,.28,.17,shirt,.07);const arms=[];for(let side of [-1,1]){let pivot=new THREE.Group();pivot.position.set(side*.142,.43,0);body.add(pivot);box(pivot,0,-.09,0,.072,.19,.077,shirt,.03);sphere(pivot,0,-.197,0,.041,skin);arms.push(pivot)}const legs=[];for(let side of [-1,1]){let pivot=new THREE.Group();pivot.position.set(side*.068,.22,0);body.add(pivot);box(pivot,0,-.075,0,.085,.17,.09,girl?'#aa7155':'#718b87',.025);box(pivot,0,-.175,.028,.098,.065,.145,'#f3e7c9',.025);legs.push(pivot)}const ring=new THREE.Mesh(new THREE.RingGeometry(.2,.235,40),new THREE.MeshBasicMaterial({color:'#ba792d',side:THREE.DoubleSide,transparent:true,opacity:.8}));ring.rotation.x=-Math.PI/2;ring.position.y=.019;root.add(ring);const held=new THREE.Group();held.position.set(0,.34,.22);body.add(held);box(held,0,0,0,.22,.022,.15,'#b57358');box(held,0,.015,0,.19,.016,.14,'#f6e2ad');held.visible=false;const cup=cyl(body,.17,.33,.12,.028,.075,'#f0dbaa');cup.visible=false;return{root,body,arms,legs,ring,held,cup,x,z,girl,path:[],auto:true,action:null,timer:3+Math.random()*4,status:'在家里散步',wait:0,manualUntil:0,routineIndex:0,seatOffset:new THREE.Vector3()}}
const people=[makePerson(false,1.03,5.08),makePerson(true,1.1,6.23)];
function release(p){p.action=null;p.seatOffset.set(0,0,0);p.held.visible=false;p.cup.visible=false}
function moveTo(p,x,z,act=null){release(p);let route=findPath(p.x,p.z,x,z);if(route===null){if(p===people[selected])toast('这里没有可通行的位置，请点空地。');return false}p.path=route;p.pending=act;p.status='正走向'+(act?act.label.replace(/^(去|到)/,''):rooms.find(r=>r.id===roomAt(x,z))?.name??'目的地');p.manualUntil=performance.now()+14000;p.wait=0;return true}
function doActivity(id){const a=activities.find(a=>a.id===id);if(a)moveTo(people[selected],...a.point,a)}
function finishActivity(p){p.action=p.pending;p.pending=null;p.timer=8+Math.random()*10;if(p.action){p.status=p.action.status;p.root.rotation.y=p.action.angle;if(p.action.id==='study'){state.computer=true;if(hour<7||hour>17)state.desk=true;updateLights()}if(p.action.id==='rest')p.seatOffset.set(.32,.25,0);if(p.action.id==='read')p.seatOffset.set(-.39,.11,0);if(p.action.id==='study')p.seatOffset.set(0,.11,0);p.seatOffset.applyAxisAngle(new THREE.Vector3(0,1,0),-p.action.angle)}else p.status='停下来看看小家'}
function chooseActivity(p){let choices=activities.filter(a=>!people.some(q=>q!==p&&(q.action?.id===a.id||q.pending?.id===a.id)));if(routine!=='random'){const seq=routine==='study'?['study','water','rest']:['rest','view','water'];let choice=choices.find(a=>a.id===seq[p.routineIndex++%seq.length]);if(choice)return moveTo(p,...choice.point,choice)}if(choices.length){let a=choices[Math.floor(Math.random()*choices.length)];moveTo(p,...a.point,a)}}
const keys=new Set();window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||$('modal').open)return;if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){keys.add(e.key);e.preventDefault()}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());document.querySelectorAll('[data-dir]').forEach(btn=>{const key={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[btn.dataset.dir];btn.onpointerdown=e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);keys.add(key)};btn.onpointerup=btn.onpointercancel=()=>keys.delete(key)});
function animatePerson(p,dt,t){let manual=p===people[selected]&&keys.size&&!planMode&&!$('modal').open,walking=false;if(manual){release(p);p.path=[];p.pending=null;p.manualUntil=t+12000;let dx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),dz=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);const fwd=new THREE.Vector3();camera.getWorldDirection(fwd);fwd.y=0;fwd.normalize();const right=new THREE.Vector3(-fwd.z,0,fwd.x),v=right.multiplyScalar(dx).add(fwd.multiplyScalar(-dz)).normalize().multiplyScalar(dt*.72);v.x=-v.x;const nx=p.x+v.x,nz=p.z+v.z;const other=people.find(q=>q!==p);if(canStand(nx,nz)&&Math.hypot(nx-other.x,nz-other.z)>.26){p.x=nx;p.z=nz;walking=true;p.root.rotation.y=Math.atan2(v.x,v.z);p.status='跟着你，在家里走走'}else p.status='前面有家具、墙壁或另一位小人'}else if(p.path.length){let [x,z]=p.path[0],dx=x-p.x,dz=z-p.z,dist=Math.hypot(dx,dz);const amount=Math.min(dist,dt*.63),nx=p.x+dx/(dist||1)*amount,nz=p.z+dz/(dist||1)*amount;let blocked=people.some(q=>q!==p&&Math.hypot(nx-q.x,nz-q.z)<.255);if(blocked){p.wait+=dt;if(p.wait>2.5&&p.auto){p.path=[];p.pending=null;p.timer=.1;p.manualUntil=0;p.wait=0}}else{p.wait=0;if(canStand(nx,nz)){p.x=nx;p.z=nz;walking=dist>.01;p.root.rotation.y=Math.atan2(dx,dz)}else{p.path=[];p.pending=null;p.timer=1}if(dist<.035)p.path.shift();if(!p.path.length)finishActivity(p)}}else{p.timer-=dt;if(p.auto&&p.timer<0&&t>p.manualUntil)chooseActivity(p)}p.root.position.set(p.x,THREE.MathUtils.damp(p.root.position.y,floorHeight(p.x,p.z),18,dt),p.z);p.ring.position.y=floorHeight(p.x,p.z)-p.root.position.y+.019;p.body.position.lerp(p.seatOffset,Math.min(1,dt*6));p.body.position.y+=walking?Math.sin(t*.014)*.0015:Math.sin(t*.0018)*.0003;const seated=['sit','read','rest'].includes(p.action?.pose);for(let i=0;i<2;i++){p.legs[i].rotation.x=seated?-Math.PI/2:walking?Math.sin(t*.013+i*Math.PI)*.42:0;p.arms[i].rotation.x=walking?-Math.sin(t*.013+i*Math.PI)*.35:p.action?.pose==='drink'&&i===1?-1.5:seated?-1.1:p.action?.pose==='wash'?-1.15+Math.sin(t*.008)*.08:0}// Feet track each side of the riser independently while the body changes height smoothly.
for(let i=0;i<2;i++){const leg=p.legs[i];if(seated){leg.position.y=.22;continue}const a=leg.rotation.x,localX=i===0?-.068:.068,localZ=.028*Math.cos(a)-.175*Math.sin(a),yaw=p.root.rotation.y;const fx=p.x+localX*Math.cos(yaw)+localZ*Math.sin(yaw),fz=p.z-localX*Math.sin(yaw)+localZ*Math.cos(yaw);const footGround=floorHeight(fx,fz),swing=walking?Math.max(0,Math.sin(t*.013+i*Math.PI))*.025:0;leg.position.y=footGround-p.root.position.y-p.body.position.y+.175*Math.cos(a)+.028*Math.sin(a)+.034+swing;}
p.held.visible=p.action?.pose==='read';p.cup.visible=p.action?.pose==='drink';p.root.visible=!planMode&&(focused==='all'||roomAt(p.x,p.z)===focused);p.ring.visible=p===people[selected]}
function updateLights(){for(const[id,o]of Object.entries(lamps)){o.light.intensity=state[id]?o.power:0;if(o.material)o.material.emissiveIntensity=state[id]?1.4:0}screenMat.emissiveIntensity=state.computer?.65:0;screenMat.color.set(state.computer?'#9dbeb6':'#35443f');document.querySelectorAll('.toggle').forEach(b=>{b.classList.toggle('on',state[b.dataset.light]);b.setAttribute('aria-pressed',String(state[b.dataset.light]))})}
const lightNames={entry:'玄关灯',kitchen:'厨房灯',wash:'洗面室灯',bath:'浴室灯',living:'卧室灯',desk:'书桌台灯'};
$('lightControls').innerHTML=Object.entries(lightNames).map(([id,name])=>`<div class="light-row"><span>${name}</span><button class="toggle" data-light="${id}" aria-label="${name}" aria-pressed="false"></button></div>`).join('');document.querySelectorAll('[data-light]').forEach(b=>b.onclick=()=>{state[b.dataset.light]=!state[b.dataset.light];updateLights()});updateLights();
const focusTarget=new THREE.Vector3(1.5,.15,4.3),focusPosition=new THREE.Vector3(10,13,-8);let cameraTween=false;
function focusRoom(id){focused=id;const r=rooms.find(r=>r.id===id);$('roomTitle').textContent=r.name;$('roomSubtitle').textContent=r.title;$('roomCount').textContent=String(rooms.indexOf(r)+1).padStart(2,'0')+' — '+(id==='all'?'OUR HOME':'A LITTLE CORNER');document.querySelectorAll('[data-room]').forEach(b=>b.classList.toggle('active',b.dataset.room===id));for(const[k,g]of Object.entries(groups))g.visible=id==='all'||k===id;for(const m of world.children)if(m.isMesh)m.visible=id==='all';outside.visible=id==='all'||id==='living'||id==='balcony';const[a,b,c,d]=r.rect;focusTarget.set(planToWorldX((a+c)/2),.25,(b+d)/2);const size=Math.max(c-a,d-b);focusPosition.copy(focusTarget).add(new THREE.Vector3(.85,1.05,-1.25).multiplyScalar(id==='all'?9.1:size*1.5));cameraTween=true;updateContext();renderPlan();if(planMode)showPlan(false)}
$('rooms').innerHTML=rooms.map(r=>`<button data-room="${r.id}" class="${r.id==='all'?'active':''}"><span class="room-icon">${r.icon}</span>${r.name}</button>`).join('');document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>focusRoom(b.dataset.room));
function updateContext(){const r=rooms.find(r=>r.id===focused);$('contextText').textContent=focused==='all'?'点击房间看细节，点击地板让小人走过去。':focused==='living'?'电脑、台灯和书本都可以点。也可以坐下来休息。':focused==='bath'?'点浴缸可放水；灯光可以单独开关。':focused==='kitchen'?'在熟悉的厨房里，给自己倒杯水。':'让小人沿着家里的通道走到这里。';let buttons=[];if(focused!=='all')buttons.push(`<button data-go="${focused}">让小人走过来</button>`);for(const a of activities.filter(a=>a.room===focused))buttons.push(`<button data-activity="${a.id}">${a.label}</button>`);if(focused==='living')buttons.push('<button data-open="computer">打开电脑</button>');buttons.push(`<button id="switchPerson">${selected===0?'👦 小男孩':'👧 小女孩'} · 切换</button>`);buttons.push(`<button id="mobileAuto">${people[selected].auto?'暂停':'开启'}自由生活</button>`);$('actions').innerHTML=buttons.join('');$('actions').querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{const r=rooms.find(r=>r.id===b.dataset.go);moveTo(people[selected],...r.target)});$('actions').querySelectorAll('[data-activity]').forEach(b=>b.onclick=()=>doActivity(b.dataset.activity));$('actions').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>interaction('computer'));$('switchPerson').onclick=()=>selectPerson(1-selected);$('mobileAuto').onclick=toggleAuto}
function selectPerson(i){selected=i;$('boy').classList.toggle('active',i===0);$('girl').classList.toggle('active',i===1);$('auto').textContent='自由生活 · '+(people[i].auto?'开启':'暂停');updateContext()}
function toggleAuto(){const p=people[selected];p.auto=!p.auto;if(!p.auto){p.path=[];p.pending=null;p.status='等你带我走走'}else{p.timer=.1;p.manualUntil=0}selectPerson(selected)}$('boy').onclick=()=>selectPerson(0);$('girl').onclick=()=>selectPerson(1);$('auto').onclick=toggleAuto;$('routine').onchange=e=>{routine=e.target.value;people.forEach(p=>{p.routineIndex=0;p.timer=.1})};updateContext();
function showModal(html){$('modalContent').innerHTML=html;$('modal').showModal();keys.clear()}$('closeModal').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').close()});
function interaction(id){if(id.startsWith('light:')){const key=id.split(':')[1];state[key]=!state[key];updateLights();toast(lightNames[key]+(state[key]?'亮起来了':'关上了'));return}if(['rest','read'].includes(id)){doActivity(id);return}if(id==='computer'){state.computer=true;updateLights();showModal('<h2>窗边的电脑</h2><p>屏幕亮起来了。今天想记下什么？</p><div class="computer-screen"><small>OUR LITTLE HOME / NOTES</small><h3>有你在，哪里都是家。</h3><textarea id="notes" placeholder="写下一点今天的小事…（保存在这台设备）"></textarea></div><p><button class="soft-button" id="studyNow">让小人坐下来学习</button></p><button class="soft-button" id="computerOff">关闭电脑</button>');const notes=$('notes');try{notes.value=localStorage.getItem('little-home-note')||''}catch{}notes.oninput=()=>{try{localStorage.setItem('little-home-note',notes.value)}catch{}};$('studyNow').onclick=()=>{doActivity('study');$('modal').close()};$('computerOff').onclick=()=>{state.computer=false;updateLights();$('modal').close()};return}if(id==='fridge'){toast('冰箱旁边歇一下，去厨房喝杯水吧。');doActivity('water')}if(id==='bathWater'){water.visible=!water.visible;toast(water.visible?'浴缸放好了温水':'浴缸里的水排掉了')}}
$('help').onclick=()=>showModal('<h2>在小家里，慢慢逛</h2><ul><li>点左侧房间，单独拿出这个角落；点「整个小家」回到完整户型。</li><li>按住鼠标或单指拖动旋转；滚轮或双指缩放。右键拖动平移。</li><li>点击空地，小人会沿通道绕开家具走过去；WASD、方向键或右下角按钮也能控制。</li><li>选择小男孩或小女孩。开启「自由生活」后，暂时不操作，小人会自己学习、喝水、休息。</li><li>点电脑可打开屏幕与记事本；点台灯或右侧开关可控制灯光。</li><li>拖动时间滑杆，或者等待一天流动（约 8 分钟一天）；晴、阴、雨会改变窗外光线。</li><li>卫生间与浴室没有可见外窗，依靠室内灯照明。</li></ul><button class="soft-button" id="showEvidence">照片与还原说明</button>');$('help').addEventListener('click',()=>{if($('showEvidence'))$('showEvidence').onclick=showEvidence});
function showEvidence(){const photos=[['1756','原始户型图'],['IMG_5115','玄关与鞋柜'],['IMG_5116','走廊与厨房'],['IMG_5118','灶台、水槽与冰箱'],['IMG_5120','卧室面向阳台'],['IMG_5121','床与入口方向'],['IMG_5122','洗面室收纳角'],['IMG_5124','洗手台与马桶'],['IMG_5125','由洗面室进入浴室'],['IMG_5126','独立浴室与浴缸']];showModal('<h2>小家是这样拼起来的</h2><p><b>空间关系以你的现场更正为准，结合户型图与实景照片还原。</b>站在玄关朝屋内看，左手边是厨房，右手边是洗面区和浴室。默认视角及平面图均按这个方向展示。玄关是较低的落尘区，进入室内需要上一级台阶。入口 → 走廊式厨房 → 约 6.1 帖的生活区 → 阳台。走廊右侧进入洗面／卫生间，再由这里进入独立浴室。床位于朝阳台看去的右侧，书桌在阳台窗前，左侧是衣架和折叠椅。</p><p>图纸上方的 MB 是管井，不作为可进入房间。洗面室收纳按照片表现，未凭图纸添加洗衣机。照片中没有沙发或独立书房，因此休息使用床边，学习使用窗前书桌。</p><p><b>估算项：</b>玄关高差暂按约 14 厘米示意；墙长、家具尺寸和层高按图纸比例与照片估计，不是实测尺寸。浴室图纸标有 1014，本模型为 Q 版比例重建。阳台照片不足，栏杆和室外机采用简化示意。外景、两位小人和书桌台灯是为交互加入的元素。日照是艺术化昼夜模拟，未校准实际朝向或地理位置。</p><p>模型只在阳台侧保留照片可确认的外窗；屋顶移除、近侧墙自动淡化便于观察。没有给厨房、卫生间或浴室新增外窗。</p><div class="gallery">'+photos.map(([file,title])=>`<figure><a href="photos/${file}.jpeg" target="_blank" rel="noopener"><img src="photos/${file}.jpeg" alt="${title}" loading="lazy"></a><figcaption>${title}</figcaption></figure>`).join('')+'</div>')}$('evidence').onclick=showEvidence;
const svgns='http://www.w3.org/2000/svg';function svg(tag,attrs,text){attrs={...attrs};if(tag==='rect')attrs.y=8.6-Number(attrs.y)-Number(attrs.height);if(tag==='text')attrs.y=8.6-Number(attrs.y);if(tag==='line'){attrs.y1=8.6-Number(attrs.y1);attrs.y2=8.6-Number(attrs.y2)}if(tag==='path')attrs.transform='translate(0 8.6) scale(1 -1)';const el=document.createElementNS(svgns,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(text)el.textContent=text;return el}
function renderPlan(){const p=$('planSvg');p.replaceChildren();for(const r of rooms.slice(1)){const[a,b,c,d]=r.rect;const rect=svg('rect',{x:a,y:b,width:c-a,height:d-b,fill:r.id===focused?'#ebc784':r.id==='bath'?'#deddd0':r.id==='wash'?'#e2d7bc':'#efdbb3',stroke:'#bca47d','stroke-width':.018,class:'plan-room'});rect.onclick=()=>focusRoom(r.id);p.appendChild(rect)}for(const[a,b,c,d,id]of obstacles){p.appendChild(svg('rect',{x:a,y:b,width:c-a,height:d-b,rx:.025,fill:id==='bed'?'#9ab6ba':id==='MB'?'#c1bcac':id==='counter'?'#96816a':'#c4ac82',stroke:'#a58b65','stroke-width':.012}));const names={bed:'床',desk:'书桌 / 电脑',rack:'衣架',counter:'厨房台面',fridge:'冰箱',tub:'浴缸',toilet:'马桶',basin:'洗手台',shoe:'鞋柜',laundry:'收纳',MB:'MB',chair:'椅',acUnit:'室外机'};p.appendChild(svg('text',{x:(a+c)/2,y:(b+d)/2+.025,class:'plan-label plan-small'},names[id]))}for(const[a,b,c,d]of walls)p.appendChild(svg('line',{x1:a,y1:b,x2:c,y2:d,stroke:'#826e51','stroke-width':.052,'stroke-linecap':'round'}));p.appendChild(svg('line',{x1:0,y1:7.7,x2:3,y2:7.7,stroke:'#93b8b4','stroke-width':.048}));p.appendChild(svg('line',{x1:0,y1:8.6,x2:3,y2:8.6,stroke:'#a79370','stroke-width':.035}));for(const[x,z,w,a]of [[.43,0,.93,0],[1.55,1.47,.8,-Math.PI/2],[1.71,2.7,.7,0],[.63,4.3,.8,0]]){const x2=x+Math.cos(a)*w,z2=z-Math.sin(a)*w;p.appendChild(svg('path',{d:`M ${x} ${z} L ${x+Math.sin(a)*w} ${z+Math.cos(a)*w} M ${x2} ${z2} Q ${x2+Math.sin(a)*w} ${z2+Math.cos(a)*w} ${x+Math.sin(a)*w} ${z+Math.cos(a)*w}`,fill:'none',stroke:'#bb9b69','stroke-width':.018,'stroke-dasharray':'.045 .028'}))}p.appendChild(svg('line',{x1:0,y1:entryStep.z,x2:entryStep.width,y2:entryStep.z,stroke:'#9c622c','stroke-width':.045}));p.appendChild(svg('text',{x:.92,y:1.2,class:'plan-label plan-small'},'↑ 上台阶 · 室内较高'));const labels=[['下沉玄关',.98,.65],['厨房 / 走廊',1.05,2.75],['洗面・卫生间',2.03,1.3],['独立浴室',2.26,3.2],['生活区 · 约6.1帖',1.1,6.48],['阳台',1.7,8.18]];for(const[text,x,y]of labels)p.appendChild(svg('text',{x,y,class:'plan-label'},text));p.appendChild(svg('text',{x:1.2,y:-.2,class:'plan-label'},'入户 ↑ 面向室内'));p.appendChild(svg('text',{x:1.55,y:8.94,class:'plan-label plan-small'},'进门看：左厨房 · 右洗面 / 浴室'))}
// Explicit handlers keep plan and 3D synchronized without moving the residents.
function showPlan(on){planMode=on;$('plan').hidden=!on;$('viewPlan').classList.toggle('active',on);$('view3d').classList.toggle('active',!on);$('canvasHost').style.visibility=on?'hidden':'visible';$('actionCard').hidden=on;document.querySelector('.dpad').hidden=on;$('hint').hidden=on;document.querySelector('.world-tools').hidden=on;if(on)renderPlan()};$('viewPlan').onclick=()=>showPlan(true);$('view3d').onclick=()=>showPlan(false);$('reset').onclick=()=>focusRoom(focused);$('walls').onclick=()=>{fullWalls=!fullWalls;toast(fullWalls?'完整墙体 · 可旋转查看':'观察模式 · 近侧墙体淡化')};
$('time').oninput=e=>{hour=+e.target.value;updateSky()};$('timePlay').onclick=()=>{timeRunning=!timeRunning;$('timePlay').textContent=timeRunning?'Ⅱ 暂停时间':'▷ 时间流动'};document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{hour=+b.dataset.time;$('time').value=hour;updateSky()});document.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{weather=b.dataset.weather;document.querySelectorAll('[data-weather]').forEach(a=>a.classList.toggle('active',a===b));updateSky()});
function updateSky(){const daylight=Math.max(0,Math.sin((hour-6)/12*Math.PI)),dusk=Math.exp(-(((hour-18)/1.2)**2))+Math.exp(-(((hour-6)/1.1)**2)),cloudFactor=weather==='sun'?1:weather==='cloud'?.47:.26;sun.intensity=daylight*3.5*cloudFactor;sun.color.set(dusk>.2?'#ffc07d':'#fff0cd');sun.position.set(1.5+Math.cos((hour-6)/12*Math.PI)*6,1+daylight*7,12);hemi.intensity=.18+daylight*.95*cloudFactor;moonLight.intensity=daylight<.05?.32:.04;const bg=new THREE.Color('#17253a').lerp(new THREE.Color(weather==='sun'?'#efd8aa':'#b9bcae'),Math.min(1,daylight*2));if(dusk>.15)bg.lerp(new THREE.Color('#dba777'),dusk*.45);scene.background.copy(bg);stage.material.color.copy(bg.clone().lerp(new THREE.Color('#c4ac81'),.22));moon.visible=daylight<.07;sunOrb.visible=daylight>.02&&weather==='sun';sunOrb.position.y=1.2+daylight*3;rain.visible=weather==='rain';clouds.forEach(g=>g.visible=weather!=='sun'||daylight>.1);$('clock').textContent=String(Math.floor(hour)).padStart(2,'0')+':'+String(Math.floor(hour%1*60)).padStart(2,'0');$('phase').textContent=hour<5?'安静的深夜':hour<9?'晨光刚刚好':hour<16?'明亮的白天':hour<18?'温柔的下午':hour<20?'落日的余温':'月光落在窗边';$('skyIcon').textContent=weather==='rain'?'☂':weather==='cloud'?'☁':daylight<.05?'☾':'☀';document.querySelector('.world').style.color=daylight<.2?'#e9cf9f':'';}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;renderer.domElement.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,time:performance.now()};cameraTween=false});function actuallyVisible(o){while(o){if(!o.visible)return false;o=o.parent}return true}renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6||performance.now()-down.time>450)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(interactables.filter(actuallyVisible),false);if(hits.length){interaction(hits[0].object.userData.action);return}const floorHits=raycaster.intersectObjects(floors.filter(actuallyVisible),false);if(floorHits.length){const h=floorHits[0];if(e.shiftKey||e.detail===2){focusRoom(h.object.userData.room);return}moveTo(people[selected],worldToPlanX(h.point.x),h.point.z)}});renderer.domElement.addEventListener('dblclick',e=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(floors.filter(actuallyVisible),false);if(hits[0])focusRoom(hits[0].object.userData.room)});
function resize(){const rect=$('canvasHost').getBoundingClientRect();renderer.setSize(rect.width,rect.height);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('canvasHost'));resize();renderPlan();updateSky();$('loading').hidden=true;
let last=performance.now(),uiAccumulator=0;function frame(t){requestAnimationFrame(frame);const dt=Math.min((t-last)/1000,.045);last=t;if(document.hidden)return;if(timeRunning&&!$('modal').open){hour=(hour+dt*.05)%24;uiAccumulator+=dt;if(uiAccumulator>.2){$('time').value=hour;updateSky();uiAccumulator=0}}people.forEach(p=>animatePerson(p,dt,t));$('activity').textContent=(selected===0?'小男孩':'小女孩')+' · '+people[selected].status;for(const d of doors){const near=people.some(p=>Math.hypot(p.x-d.x,p.z-d.z)<1.05);let desired=d===doors[0]?d.base:(d.base+(near?-Math.PI*.46:0));d.pivot.rotation.y=THREE.MathUtils.damp(d.pivot.rotation.y,desired,8,dt)}for(const m of wallMeshes){const[a,b,c,d]=m.userData.bound;const rr=rooms.find(r=>groups[r.id]===m.parent)?.rect??[0,0,3,8.6],cx=worldToPlanX(camera.position.x);let near=a===c?(a<=(rr[0]+rr[2])/2?cx<a:cx>a):(b<=(rr[1]+rr[3])/2?camera.position.z<b:camera.position.z>b);let opacity=fullWalls?1:near?.09:1;m.material.opacity=THREE.MathUtils.damp(m.material.opacity,opacity,8,dt);m.material.depthWrite=m.material.opacity>.9;m.castShadow=true}if(cameraTween){camera.position.lerp(focusPosition,Math.min(1,dt*5));controls.target.lerp(focusTarget,Math.min(1,dt*5));if(camera.position.distanceTo(focusPosition)<.02)cameraTween=false}controls.update();if(rain.visible){const a=rainGeo.attributes.position;for(let i=0;i<420;i++){a.array[i*3+1]-=dt*3.1;if(a.array[i*3+1]<-.1)a.array[i*3+1]=5}a.needsUpdate=true}water.position.y=.48+Math.sin(t*.002)*.003;if(!planMode)renderer.render(scene,camera)}requestAnimationFrame(frame);
window.addEventListener('error',()=>{if(!$('loading').hidden){$('loading').hidden=true;$('sceneError').hidden=false}});
